### PR TITLE
Updating to latest imgui master

### PR DESCRIPTION
**Pull request by Pagghiu**
- Switching rendering to indexed primitives both in the server (cpp) and client (js)
- Adding VS2015 project
- Removing glew as it doesn't look necessary for the example
- Tweaking .gitignore file

### CODE REVIEW

**Comment by ocornut** [comment]
Cool. Haven't used this for a while myself (but I reckon they are using it at Media Molecule)
Perhaps move imgui into a git subrepository? Would make clarifying what's part of the "remote" package as well.

**Comment by Pagghiu** [comment]
Sure,
let's see if the repo owner has anything to say and I can make it (or at least try...I'm so scared to get everything wrong with these advanced git-fu combos =D)

**Comment by ocornut** [comment]
I think Jordi is moving countries and making new babies so I imagine he'll be super busy for a while. Maybe he can confirm? Perhaps it wouldn't be a bad idea if your repo took the lead on this project if you are interested in polishing it.

**Comment by Pagghiu** [comment]
Ok, no big deal, code is pretty simple, I will have a look at the input handling and git sub-repository.

**Comment by Pagghiu** [comment]
I've been pushing some of the above mentioned tasks. 
FYI, the vs2010 vcproj is untested (I only have vs2013 installed).

**Comment by JordiRos** [comment]
Thanks Pagghiu! Sorry for the late reply, been busy with lots of stuff lately. Will test it and merge asap :)

**Comment by Pagghiu** [comment]
You're welcome, I've also updated to latest imgui as of today and quickly tested :+1:

**Pull request merged**
